### ISSUE TITLE
git history

### ISSUE THREAD

**Issue by DarthGandalf** [XPhyro/htop-xphyro#1]
Hi, why you didn't preserve old htop git history?

**Comment by XPhyro** [comment]
I did not think it would be necessary as one could look at the original repository, thus I chose the easy option of just removing the .git directory and executing git init.

**Comment by DarthGandalf** [comment]
But not deleting it is even easier

**Comment by XPhyro** [comment]
I already had the repository cloned locally. As far as I know, in the terminal, it requires more work to fork a repository than to initiate another one; and I did not want to open GitHub.

If it is possible to initiate a new repository while keeping the history (without forking), I do not know of such a method.

**Comment by DarthGandalf** [comment]
No, you simply don't delete .git, that's it

You can have several remotes in the same repo, e.g. if `origin` was in https://github.com/hishamhm/htop you could do e.g.

```sh
git remote add my git@github.com:XPhyro/htop-xphyro.git
git push my master
git remote -v
```

**Comment by XPhyro** [comment]
I did not know remotes worked like that. I thought it would initiate from scratch if I added a new remote, somewhat like having two repositories in the same directory. As I did not need the old remote and thought there would be no difference in the new remote, I just removed .git.

Thanks for the heads-up.

**Comment by DarthGandalf** [comment]
Well, I advice you to bring old code back, because now this fork is incompatible with other ones (no way to do e.g. pull request)

And it's not obvious what the patches in the initial commits were.

**Comment by XPhyro** [comment]
Sure, makes sense. I'll soon do so when I find some time for it.

**Comment by XPhyro** [comment]
Original history is merged, closing.
